default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= (ENV['CONTEXT_SERVER_THREADS'].to_i + 2) || 4 %>

development:
  <<: *default
  database: context_development
  personname: context
  password: password

test:
  <<: *default
  url:  <%= ENV["CONTEXT_DATABASE_URL_TEST"] %>

production:
  <<: *default
  url:  <%= ENV["CONTEXT_DATABASE_URL"] %>

# benchmark:
#   <<: *default
#   url:  <%= ENV["CONTEXT_DATABASE_URL"] %>
