default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['HEALTHCREEK_SERVER_THREADS'] || 4 %>

development:
  <<: *default
  database: healthcreek_development
  username: healthcreek
  password: password

test:
  <<: *default
  url:  <%= ENV["HEALTHCREEK_DATABASE_URL_TEST"] %>

production:
  <<: *default
  url:  <%= ENV["HEALTHCREEK_DATABASE_URL"] %>

# benchmark:
#   <<: *default
#   url:  <%= ENV["HEALTHCREEK_DATABASE_URL"] %>
